{% set version = "2.4.3" %}

package:
  name: libharu
  version: {{ version }}

source:
  url: https://github.com/libharu/libharu/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a2c3ae4261504a0fda25b09e7babe5df02b21803dd1308fdf105588f7589d255

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - ninja
  host:
    - zlib
    - libpng

test:
  commands:
    - test -f $PREFIX/include/hpdf.h  # [unix]
    - test -f $PREFIX/lib/libhpdf${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\hpdf.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\hpdf.dll exit 1  # [win]

about:
  home: http://libharu.org/
  license: Zlib
  license_family: OTHER
  license_file: LICENSE.txt
  summary: |
      libharu is a free, cross platform, open source library for generating PDF
      files.
  doc_url: https://github.com/libharu/libharu/wiki
  dev_url: https://github.com/libharu/libharu


extra:
  recipe-maintainers:
    - hobu
    - xylar
