{% set version = "2.4.5" %}

package:
  name: libharu
  version: {{ version }}

source:
  url: https://github.com/libharu/libharu/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0ed3eacf3ceee18e40b6adffbc433f1afbe3c93500291cd95f1477bffe6f24fc

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libharu', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - zlib
    - libpng

test:
  commands:
    - test -f $PREFIX/include/hpdf.h  # [unix]
    - test -f $PREFIX/lib/libhpdf${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\hpdf.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\hpdf.dll exit 1  # [win]

about:
  home: http://libharu.org/
  license: Zlib
  license_family: OTHER
  license_file: LICENSE.txt
  summary: |
    libharu is a free, cross platform, open source library for generating PDF
    files.
  doc_url: https://github.com/libharu/libharu/wiki
  dev_url: https://github.com/libharu/libharu


extra:
  recipe-maintainers:
    - hobu
    - xylar
